version: '3'

services:
  app:
    build: .
    container_name: chatroom-web
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    command: ["poetry", "run", "daphne", "-p", "8000", "chatroom.asgi:application", "-b", "0.0.0.0"]
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydatabase
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    networks:
      - backend

  db:
    image: postgres:latest
    container_name: chatroom-db
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: chatroom-redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
