# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-$ENVIRONMENT_NAME
  namespace: default
  labels:
    app: my-app-$ENVIRONMENT_NAME
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app-$ENVIRONMENT_NAME
  template:
    metadata:
      labels:
        app: my-app-$ENVIRONMENT_NAME
    spec:
      containers:
        - name: my-app-container
          image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
          ports:
            - containerPort: 8000
          env:
            - name: ENVIRONMENT
              value: $ENVIRONMENT_NAME
          livenessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
